version: "3.9"
services:
  web:
    build: .
    container_name: appchat
    ports:
      - "3000:3000" 
    networks:
      - example-net
  nginx:
    build:  
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    hostname: nginx
    ports:
        - "80:80" 
    depends_on:
      - web
    networks:
      - example-net

networks:
  example-net:
    driver: bridge
    